### PR TITLE
[MARCHETYPES-75] Bump web archetype deployment descriptor to v4, portlet to v3

### PR DESCRIPTION
**Pull request by nitind**
Generated webapps will refer to the web-app 4.0 schema, portlets to
the portlet 3.0 schema and corresponding web-app 3.1 schema.

### CODE REVIEW

**Review by AnEmortalKid — APPROVED** [review]

**Comment by AnEmortalKid** [comment]
@hboutemy any chance this could be merged ?

**Comment by slawekjaranowski** [comment]
Please create jira issue for it.

**Comment by nitind** [comment]
Servlet 5 involved API breakages, so still putting forth this change to 4.0.

**Comment by nitind** [comment]
@slawekjaranowski Opened [MARCHETYPES-75](https://issues.apache.org/jira/browse/MARCHETYPES-75)

**Comment by jira-importer** [comment]
Resolve #56

**Pull request merged**
