### PR TITLE
[MARCHETYPES-78] Set Java 8 as default Java version in archetype created projects instead of Java 7

### PR DESCRIPTION
**Pull request by judovana**
hi!

Similarly as in https://github.com/apache/maven-archetypes/pull/18 the jdk7 bytecode is no longr viable in jdk21 world, and no one should be using jdk7. 
Thus - much more simple then https://github.com/apache/maven-archetypes/pull/18 - bulk bump of 1.7 maven compiler settings to 1.8
I can not swear that I had not missed any, but I did my best to not miss any.

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/MARCHETYPES/issues/MARCHETYPES-78) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MARCHETYPES-XXX] SUMMARY`, where you replace `MARCHETYPES-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by slachiewicz** [comment]
what is the difference between this jira and the previous one [MARCHETYPES-78](https://issues.apache.org/jira/browse/MARCHETYPES-78) #18  ?

imho too many tickets with the same scope, "archetypes generate EOLed maven.compiler versions" Previously You have changed it to Java 7 and renamed directories also.

**Comment by judovana** [comment]
The https://github.com/apache/maven-archetypes/pull/18 was focusing only onec archetypes component - the quickstasrt - I did ti first, as it was a bit more compelx then the others.

This one is handling all others archetypes components. The original jira was named properly "maven-archetype-quickstart  ...." - https://issues.apache.org/jira/browse/MARCHETYPES-76

The scond one https://issues.apache.org/jira/browse/MARCHETYPES-78 is handling all others.

**Comment by slachiewicz** [comment]
superseded by #22

**Comment by judovana** [comment]
> superseded by #22

Sorry it is not surpassed. It is doing revert of good thing and is mixing several parts together. 

I think it would be better to propose https://github.com/apache/maven-archetypes/pull/22/commits/6141badd9d7d3c90e51cfe6ec414b6a7fb2b25f5 as standalone PR. Merge that. And then merge this one

**Comment by judovana** [comment]
I see you have closed #22 , thank you. Can we reopen this please?

**Comment by elharo** [comment]
While I have no objection to selecting Java 8 by default instead of Java 7, I feel I need to keep repeating that Java 7 is not end of life. It is supported by and available from multiple vendors. Oracle != Java.

**Comment by judovana** [comment]
> While I have no objection to selecting Java 8 by default instead of Java 7, I feel I need to keep repeating that Java 7 is not end of life. It is supported by and available from multiple vendors. Oracle != Java.

I think the pointing part is support of openjdk - last maintainer of openjdk7 was azul, and they dropped it.

**Comment by judovana** [comment]
will be reworked

**Comment by jira-importer** [comment]
Resolve #111

**Pull request closed without merging**
